### PR TITLE
Add newline after header message, before `\\ sources:`

### PR DESCRIPTION
**Pull request by LorbusChris**

### CODE REVIEW

**Comment by LorbusChris** [comment]
cc @veily 
maybe you could also cut another release with this fix? Having all the headers look that way is really unpleasant.

**Comment by LorbusChris** [comment]
friendly ping :)

**Comment by LorbusChris** [comment]
@veily any chance you can take a look? :)

**Comment by LorbusChris** [comment]
Anybody? This is a trivial fix...

**Comment by LorbusChris** [comment]
ping

**Comment by LorbusChris** [comment]
Is this project still maintained? Not getting any replies from maintainers is a bit worrying since the code here in this repo is used in many places..

**Comment by kevinburke** [comment]
I maintain kevinburke/go-bindata, FYI, which is also the one you get if you use Homebrew

**Comment by LorbusChris** [comment]
@kevinburke that's interesting. Thank you for bringing that to my attention!

**Comment by mars1024** [comment]
Just run into the same issue which already fixed by this, friendly ping @jaredallard

**Comment by jaredallard** [comment]
> Just run into the same issue which already fixed by this, friendly ping @jaredallard 

I'm not a member of this repo :D I'm all for merging it

**Comment by mars1024** [comment]
> > Just run into the same issue which already fixed by this, friendly ping @jaredallard
> 
> I'm not a member of this repo :D I'm all for merging it

sorry, :) seems this repo is not so active

**Comment by mars1024** [comment]
ping @liweiv for help

**Pull request merged**
